# Generated by Django 4.0.5 on 2022-08-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.FileField(null=True, upload_to='tesis')),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('autor', models.CharField(max_length=30)),
            ],
        ),
    ]
