# Generated by Django 4.0.5 on 2022-08-22 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesisApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Tesis',
        ),
    ]
