# Generated by Django 4.0.5 on 2022-08-07 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclos',
            fields=[
                ('idciclo', models.AutoField(primary_key=True, serialize=False)),
                ('ciclo', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('iddocente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('imagenRuta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Escuelas',
            fields=[
                ('idescuela', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=12)),
                ('visto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grado_docente',
            fields=[
                ('idgrado', models.AutoField(primary_key=True, serialize=False)),
                ('grado', models.TextField()),
                ('iddocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrerasApp.docentes')),
            ],
        ),
        migrations.CreateModel(
            name='Exp_lab',
            fields=[
                ('idexp', models.AutoField(primary_key=True, serialize=False)),
                ('exp', models.TextField()),
                ('iddocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrerasApp.docentes')),
            ],
        ),
        migrations.AddField(
            model_name='docentes',
            name='idEscuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrerasApp.escuelas'),
        ),
        migrations.CreateModel(
            name='Curriculas',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('codigoint', models.CharField(max_length=4)),
                ('asignatura', models.CharField(max_length=69)),
                ('creditos', models.SmallIntegerField()),
                ('condicion', models.CharField(max_length=1)),
                ('ht', models.SmallIntegerField()),
                ('hp', models.SmallIntegerField()),
                ('hl', models.SmallIntegerField()),
                ('requisito', models.CharField(max_length=19)),
                ('departamento', models.CharField(max_length=36)),
                ('idciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrerasApp.ciclos')),
                ('idescuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrerasApp.escuelas')),
            ],
        ),
    ]
