# Generated by Django 4.0.5 on 2022-08-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrerasApp', '0001_initial'),
    ]

    operations = [
    
        migrations.RenameField(
            model_name='escuelas',
            old_name='id',
            new_name='idescuela',
        ),
    ]
