# Generated by Django 4.0.5 on 2022-08-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrerasApp', '0002_rename_imagenruta_docentes_imagenruta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculas',
            name='estado',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
