# Generated by Django 4.0.5 on 2022-08-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrerasApp', '0003_alter_docentes_imagenruta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escuelas',
            old_name='idescuela',
            new_name='id',
        ),
    ]
