# Generated by Django 4.0.5 on 2022-08-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrerasApp', '0003_curriculas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculas',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
