# Generated by Django 4.0.5 on 2022-08-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrerasApp', '0003_alter_docentes_imagenruta'),
        ('carrerasApp', '0004_alter_curriculas_estado'),
    ]

    operations = [
    ]
