# Generated by Django 4.0.5 on 2022-08-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('idEscuela', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=12)),
                ('visto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idNoticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('seccion', models.TextField()),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
