# Generated by Django 4.0.5 on 2022-08-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
