# Generated by Django 4.0.5 on 2022-08-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_escuela_estado_alter_noticia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
