# Generated by Django 4.0.5 on 2022-08-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_alter_noticia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='ruta',
            field=models.ImageField(default='docentes/perfil.jpg', null=True, upload_to='docentes'),
        ),
    ]
