# Generated by Django 4.0.5 on 2022-08-07 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('seccion', models.SmallIntegerField()),
                ('fecha', models.DateTimeField()),
                ('estado', models.BooleanField(default=True)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.CharField(max_length=150)),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('seccion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias_imagenes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('idnoticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticiasApp.noticias')),
            ],
        ),
    ]
