# Generated by Django 4.0.5 on 2022-08-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticiasApp', '0003_noticias_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='ruta',
            field=models.ImageField(null=True, upload_to='noticias'),
        ),
    ]
